config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "posts#index"

  resources :posts, only: [:index] do
    resources :comments do
      resource :cancel, only: [:show], module: :comments
      resources :reactions, only: [:destroy, :update], module: :comments, shallow: true
    end
  end

  namespace :admin do
    resources :posts
  end

  get "posts/:username", to: "posts/users#index", as: "post_users", constraints: { username: /.*/ }
  get ":id/(:slug)", to: "posts#show", as: "post"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :comment_app_emojis

  delegate :email, to: :user

  has_rich_text :content

  def editable?(user)
    self.user == user
  end

  # Other options, perhaps better than this one:
  #   - use a policy pattern (like pundit gem)
  #   - the model know if its editable, but to avoid sending current_user, I would for for a Current.user
  #     (ActiveSupport::CurrentAttributes)
  def destroyable?(user)
    self.user == user || post.user == user
  end
end

app/controllers/comments/cancels_controller.rb
class Comments::CancelsController < AdminController
  def show
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:comment_id])
  end
end

app/controllers/comments/reactions_controller.rb
class Comments::ReactionsController < AdminController
  before_action :set_comment
  before_action :set_emoji

  def update
    emojis = @comment.comment_app_emojis.find_by(user: current_user, app_emoji: @app_emoji)
    @comment.comment_app_emojis.create(user: current_user, app_emoji: @app_emoji) unless emojis
  end

  def destroy
    emojis = @comment.comment_app_emojis.find_by(user: current_user, app_emoji: @app_emoji)
    @comment.comment_app_emojis.delete(emojis) if emojis
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_emoji
      @app_emoji = AppEmoji.find(params[:emoji])
    end
end

app/controllers/comments_controller.rb
class CommentsController < AdminController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update]

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post

    @comment.save!
  end

  def destroy
    # We can delete any comment if we are the post owner
    # else we can only delete our own posts

    @comment = Comment.find(params[:id])

    if @comment.destroyable?(current_user)
      @comment.delete
    else
      # It's a situation that shouldn't happen unless there is a bug or someone is messing with the HTTP request
      # we can ignore or not ... like raise an exception ...
    end
  end

  def edit
  end

  def update
    if @comment.editable?(current_user)
      @comment.update(comment_params)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

  
end

app/views/comments/_comment.html.erb
<article id="comment_<%= comment.id %>">
  <h2>#<%= comment.id %> | <%= comment.user.email %>, <%= comment.created_at if user_signed_in? %></h2>
  <%= link_to "Remove", post_comment_path(post, comment), method: :delete, remote: true, data: { confirm: 'Are you sure?', disable_with: "Removing ..." } if current_user == post.user || comment.user == current_user %> |
  <%= link_to "Edit", edit_post_comment_path(post, comment), remote:true, id: "comment_edit_#{comment.id}" if comment.editable?(current_user) %>
  <%= link_to "Cancel", post_comment_cancel_path(post, comment), remote: true, id: "comment_cancel_#{comment.id}", style: "display:none;" %></>
  <div style="margin-top: 30px; margin-bottom: 30px;">
    <div id="<%= "comment_#{comment.id}_reactions" %>">
      <%= display_emojis(comment) %>
    </div>

    <% if user_signed_in? %>
    <div x-data="{ open: false }">
      <button @click="open = true">Reaction</button>
      <ul x-show="open" @click.away="open = false">
        <% AppEmoji.all.each do |emoji| %>
          <li id="<%= "comment_#{comment.id}_emoji_#{emoji.id}_dropdown" %>">
            <%= emoji_link( comment, emoji ) %>
          </li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>

  <div id="comment_content_<%= comment.id %>">
    <%= comment.content %>
  </div>
  <br><br>
</article>

app/views/comments/_form.html.erb
<%= form_with model: [post, comment], namespace: comment.id do |form| %>
  <div class="field">
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
<% unless @comment.errors.any? %>
  document.getElementById("messages").insertAdjacentHTML("beforeend", "<%= escape_javascript(render "/comments/comment", comment: @comment, post: @post) %>");
  document.getElementById("comment_content").value=""
<% end %>

app/views/comments/destroy.js.erb
document.getElementById("comment_<%= params[:id] %>").remove();

app/views/comments/edit.js.erb
// hides edit link
document.getElementById("<%= "comment_edit_#{@comment.id}" %>").style.display = "none";

// show cancel link
document.getElementById("<%= "comment_cancel_#{@comment.id}" %>").style.display = "inline";

// injects the form
// Note: some developers will argue that innerHTML is not fast enough. There are, obviously, other ways to remove
//       the comment, like iterate alll the nodes, like using removeChild with firstChild & lastChild or
//       replace the dom with something else (replaceChild), or usinng node.remove(). so many options ...
//       innerHTML does the job, though!
var element = document.getElementById("<%= "comment_content_#{@comment.id}" %>");
element.innerHTML = "<%= escape_javascript(render "/comments/form", comment: @comment, post: @post) %>";

app/views/comments/error.js.erb
alert("You are not allowed to do that!");

app/views/comments/update.js.erb
// shows edit link
document.getElementById("<%= "comment_edit_#{@comment.id}" %>").style.display = "inline";

// hide cancel link
document.getElementById("<%= "comment_cancel_#{@comment.id}" %>").style.display = "none";

// injects the form
// Note: some developers will argue that innerHTML is not fast enough. There are, obviously, other ways to remove
//       the comment, like iterate alll the nodes, like using removeChild with firstChild & lastChild or
//       replace the dom with something else (replaceChild), or usinng node.remove(). so many options ...
//       innerHTML does the job, though!
var element = document.getElementById("<%= "comment_content_#{@comment.id}" %>");
element.innerHTML = "<%= escape_javascript(@comment.content)%>";