config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "posts#index"

  resources :posts, only: [:index] do
    resources :comments do
      resource :cancel, only: [:show], module: :comments
      resources :reactions, only: [:destroy, :update], module: :comments, shallow: true
    end
  end

  namespace :admin do
    resources :posts
  end

  get "posts/:username", to: "posts/users#index", as: "post_users", constraints: { username: /.*/ }
  get ":id/(:slug)", to: "posts#show", as: "post"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/concerns/posts/post_state_finders.rb
module Posts::PostStateFinders
  extend ActiveSupport::Concern

  class_methods do
  #  a field like :title, modality like "ASC" or "DESC"
  # Post.ordered_by(:title,"ASC")
    def ordered_by(field,modality)
      order("#{field} #{modality}")
    end

    def published
      where(["status = ?", :published])
    end

    def drafted
      where(["status = ?", :draft])
    end

    # find posts by email and status 0(draft) or 1(published)
    # Post.created_by("email@gmail.com",1)
    def created_by(email_user,status)
      joins(:user).where(["email = ? AND status = ?", email_user,status])
    end

    #find posts by searching the title
    #Post.search_by("pippo")
    def search_by(text)
      where(["title LIKE ?", "#{text}"])
    end
  end 
  
end

app/models/post.rb
class Post < ApplicationRecord
  include Posts::PostStateFinders

  enum status: { draft: 0, published: 1 }

  has_rich_text :content

  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true
  validates :publish_at, presence: true
  validates :slug, presence: true

  delegate :email, to: :user




  
  before_validation :set_slug

  private
    def set_slug
      self.slug = title.downcase.parameterize
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # @post = Post.new(post_params)
    # @post.user = current_user
    @post = current_user.posts.create(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to [:admin, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [:admin, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :status, :publish_at)
    end
end

app/controllers/posts/users_controller.rb
class Posts::UsersController < ApplicationController
  before_action :set_user

  def index
    @posts = @user.posts.includes(:comments)
  end

  private
    def set_user
      @user = User.find_by!(email: params[:username])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
     # @posts = Post.drafted
    @posts = Post.published
    @users = User.order(:email)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper


  def posts_number_by_email(user)
    user.email  +  " " + pluralize(user.posts.count, "post", "posts")
  end
end

app/views/posts/_post_resume.html.erb
<article>
  <h2><%= link_to post.title, post_path(post, post.slug) %></h2>
  <p><%= pluralize(post.comments.count, "comment", "comments") %><p>
  <br>
  <address>By <a rel="author" href=""><%= post.user.email %></a></address>
    on <time pubdate datetime="<%= post.publish_at %>" title="<%= post.publish_at %>"><%= post.publish_at %></time>
  <br><br>
  <%= truncate post.content.to_plain_text, length: 250, seperator: ' ' %>
  <hr>
</article>

app/views/posts/index.html.erb
<h1>Fancy blog system</h1>
<aside>
  <ul>
    <% @users.each do |user| %>
      
      <li><%= link_to posts_number_by_email(user), post_users_path(user.email) %></li>
    <% end %>
  </ul>
</aside>

<section>
  <%= render partial: "post_resume", collection: @posts, as: :post %>
</section>

app/views/posts/show.html.erb
<section>
  <article>
    <h1><%= @post.title %></h1>
    <br>
    <address>By <a rel="author" href=""><%= @post.user.email %></a></address>
      on <time pubdate datetime="<%= @post.publish_at %>" title="<%= @post.publish_at %>"><%= @post.publish_at %></time>
    <br><br>
    <%= @post.content %>
  </article>
</section>

<hr>

<section id="messages">
  <%= render partial: "comments/comment", collection: @post.comments, locals: { post: @post } %>
</section>

<% if user_signed_in? %>
  <%= render "comments/form", post: @post, comment: Comment.new %>
<% end %>